go.go
=> fizzbuzz golang

hoon.hoon
Urbit's lisp-y runic language. Run by putting the source in gen/fizz.hoon and running +fizz.
=> Add Hoon solution

arnoldc.arnoldc
In a momentary lapse of judgment, you forgot the obviously magnificent programming language known to man, [ArnoldC](https://github.com/lhartikk/ArnoldC). It works as given by the following output. You can get the `ArnoldC.jar` file from the repo
```
$ java -jar ArnoldC.jar fizzbuzz.arnoldc
$ java fizzbuzz
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizzbuzz
31
32
fizz
34
buzz
fizz
37
38
fizz
buzz
41
fizz
43
44
fizzbuzz
46
47
fizz
49
buzz
fizz
52
53
fizz
buzz
56
fizz
58
59
fizzbuzz
61
62
fizz
64
buzz
fizz
67
68
fizz
buzz
71
fizz
73
74
fizzbuzz
76
77
fizz
79
buzz
fizz
82
83
fizz
buzz
86
fizz
88
89
fizzbuzz
91
92
fizz
94
buzz
fizz
97
98
fizz
buzz
```
=> added arnoldc

lua.lua
=> Add Lua version

java.java
It had defined `fizzBuzz`, but never called the method.
=> make java.java work

c++.cpp
It would only print Fizz or Buzz, never FizzBuzz, similar to c.c
=> fix c++.cpp

python.py, python2.py
Rename the existing `python.py` to `python2.py`, and add a new `python.py` that works with both Python 2 and Python 3.
=> Add a script that works on both Python 2 and 3

matlab.m
=> added matlab.m

matlab.m
Before:
1
2
Fizz
4
Buzz
After:
1
2
Fizz
4
Buzz
(Note I'm actually using Octave, an open source alternative mostly compatible with the real MATLAB.)
=> Fix matlab.m alignment

crystal.cr
=> Add Crystal

ruby.rb
Make redundant #36 by making the Ruby version work with Crystal.
=> Make Ruby version compatible with Crystal

beta.bet
BETA was a object-oriented language in the SIMULA family, developed from 1975 to the 1990's in Norway.
See [HOPL](http://hopl.info/showlanguage.prx?exp=1032&language=BETA).
=> Created Fizz Buzz in the beta language

kotlin.kt
=> Add FizzBuzz in Kotlin

ocaml.ml
Execute using
`ocaml ocaml.ml`
Some references:
https://ocaml.org/
http://www2.lib.uchicago.edu/keith/ocaml-class/operators.html
http://caml.inria.fr/pub/docs/u3-ocaml/ocaml-steps.html
=> Add FizzBuzz in OCaml

assembly.asm
_Reviewer: Is this modular enough?
Me: 😨 
Reviewer: Oh S#!1 this is assembly!_
=> FizzBuzz in Assembly

labyrinth.lab
https://github.com/m-ender/labyrinth
=> Add FizzBuzz in Labyrinth

fsharp.fs
[Try it online!](https://tio.run/nexus/fs-mono#RY7NCsIwEITveYohUGihlhTxIujBQ18j@Be7oFtptwjBd4@LtvU0MPMxM@l@FQSK8TTGiJyxBbEUKoP0xDfsDPA4yrkFI8O6/MoGL5JWkzdcCYfVHrbRkoOW2Nn2i/2z/Ez@KT9R0xYbE7peF4hRo6pQO4dLp@hTcwkMmw0W@fKXi5Q@ "F# (Mono) – TIO Nexus")
=> Add FizzBuzz in F#

pinecone.pn
Slightly modified [the GitHub page](https://github.com/william01110111/Pinecone).
=> Added Pinecone.

escript.erl
Added erlscript to FizzBuzz. This answers ticket https://github.com/zenware/FizzBuzz/issues/71
=> Added erlang script

typescript.ts
=> Add typescript language

scilab.sce
There is MATLAB and Octave implementations so why not to add [Scilab](https://www.scilab.org/) one?
=> Added Scilab implementation

README.md
It has an explicit permissive licence, and test suite and CI which you
are free to reuse.
=> Add a link to the @shlomif fizz buzz.

b.b
Added the B language (the predecessor to C).
=> Added B language

buzzfizz.buzzfizz
Check the language at https://esolangs.org/wiki/BuzzFizz.
=> Add BuzzFizz implementation

Haxe.hx
Tested here: https://try.haxe.org/#a4e78
=> Haxe Fizz Buzz

enkelt.e
Added FizzBuzz for the Enkelt programming language (https://enkelt.io)
=> Added Enkelt

prolog.pl
Include implementation in prolog
=> Prolog FizzBuzz implementation

scheme.scm
Recursive implementation of FizzBuzz added in Scheme
=> Added FizzBuzz in Scheme

vala.vala
Implemented in [Vala](https://wiki.gnome.org/Projects/Vala)
=> FizzBuzz in Vala language

commodore_basic.bas
=> Commodore BASIC
